### ISSUE TITLE
Pumping rate out of the Tank

### ISSUE THREAD

**Issue by Sehtek** [fgardt/factorio-underground-storage-tank#2]
Hey there,
i just build some of the underground tanks ingame and wanted to connect them via pumps to a train.
![grafik](https://github.com/user-attachments/assets/53ab5c60-357d-4c76-a9b7-d19745d33694)

Even tho the Tanks overall have like 1M Oil in them, the pumps only pump like 120/s. Thats make loading the 50k train wagons a long process and i was wandering, if i did something wrong or this is a problem of the mod.

Thanks alot!

**Comment by fgardt** [comment]
This is definitely not expected behavior. Have you set the volume of the tanks to some custom value by chance? Cause by default these 4 tanks should allow a maximum of 1M fluid when completely full but they don't look full.

**Comment by Sehtek** [comment]
I cranked the number up a bit, so each of them can hold 10M fluid.

**Comment by Sehtek** [comment]
![grafik](https://github.com/user-attachments/assets/3e309b7d-d0c8-4b7a-a9ae-46fe8726f453)

Even if i do this (with the standard option of 250k per Tank), the pump in the middle, which pumps the fluid from the 1st to the 2nd tank, is working at a slow rate (140/s ish).

For the pump on the bottom right: The Problem was fixed by putting the capacity of the tank down. 

It seems to be effected, if you try to put multiple of those tanks together.

**Comment by fgardt** [comment]
I asked raiguard (the dev currently responsible for the 2.0 fluid mechanics) if this behavior is expected & intentional and the answer is yes.
So there is not much I can do here realistically, it'll just be something to think about when designing setups with large storage buffers.

Thanks a lot for reaching out and conducting tests tho. Thats greatly appreciated!
